# Hyperparameter Tuning with Optuna

This notebook performs hyperparameter optimization for selected models
(CatBoost, XGBoost, and Extra Trees) using Optuna.

The objective metric is **Average Precision (PR-AUC)**, which is more
appropriate for highly imbalanced classification problems such as fraud detection.

Sampling techniques and threshold tuning are intentionally excluded
at this stage to isolate the intrinsic performance of each model.

In [1]:
from datapipeline.data.load_data import load_raw_data
from datapipeline.config.mlflow_config import setup_mlflow
import yaml
import pandas as pd
import mlflow
from pathlib import Path
import optuna
from sklearn.metrics import (roc_auc_score, 
                            balanced_accuracy_score,
                            precision_score,
                            recall_score,
                            f1_score,
                            confusion_matrix,
                            precision_recall_curve,
                            average_precision_score,
                            make_scorer)
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.dummy import DummyClassifier
from lightgbm import LGBMClassifier
import xgboost as xgb
from sklearn.utils.class_weight import compute_sample_weight

In [2]:
#primary metric that will be used for model comparison
PRIMARY_METRIC = "Average Precision Score"

In [3]:
#loading config file
config_path = '../config.yaml'
with open(config_path, 'r') as f:
    config = yaml.safe_load(f)

In [37]:
random_state = config["model_training"]["random_state"]

42

In [59]:
artifacts_dir = Path(config['model_selection']['artifacts_path'])

# MLflow

In [4]:
experiment_name = config['pipeline']['experiment_name']

In [5]:
setup_mlflow(experiment_name)

In [6]:
artifacts_dir = Path(config['model_tuning']['artifacts_path'])

# Load Dataset

In [7]:
dataset_path = Path(config['feature_engineering']['train_path_feature_engineered'])
target_column = config['data']['target_column']

In [8]:
df_train = pd.read_parquet(dataset_path)

In [9]:
y_train = df_train[target_column]

In [10]:
x_train = df_train.drop(columns = ['Time', target_column])

# Models

Models selected in the previous sted:

- Catboost
- Extra Trees
- Xgboost

# Cross Validation setup

In [11]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=config["model_training"]["random_state"]
)

scoring = {
    'average_precision': 'average_precision'
          }

# Optuna objective — XGBoost

In [12]:
n_major = sum(y_train==0)
n_minor = sum(y_train==1)
scale_pos_weight = n_major / n_minor

In [13]:
def calculating_cross_validation(model):
    cv_results = cross_validate(model, 
                                x_train, 
                                y_train, 
                                cv=cv, 
                                scoring=scoring, 
                                verbose=False)
    return cv_results

In [ ]:
xgb.XGBClassifier(

In [14]:
def objective_xgboost(trial):

     params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 3, 8),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1.0, 20.0),
        "random_state": random_state,
        "scale_pos_weight": scale_pos_weight,
        "eval_metric": "aucpr",
        "tree_method": "hist"
     }

     model = xgb.XGBClassifier(**params)

     '''
     cv_results = cross_validate(model, 
                                x_train, 
                                y_train, 
                                cv=cv, 
                                scoring=scoring, 
                                verbose=False)
     '''
     cv_results = calculating_cross_validation(model)
     metrics_results = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]

     return metrics_results

In [ ]:
with mlflow.start_run(run_name="xgboost_hyperparameter_tuning"):
    study = optuna.create_study(direction='maximize')
    study.optimize(objective_xgboost, n_trials=50)

    model = xgb.XGBClassifier(scale_pos_weight=scale_pos_weight)
    cv_results = calculating_cross_validation(model)
    xgb_best_params = study.best_params
    metric_default_hyperparameters = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]

    mlflow.log_metric('average_precision_default_params', metric_default_hyperparameters[0])
    mlflow.log_metric('best_cv_average_precision', study.best_value)
    mlflow.log_params(study.best_params)

print(f'Best average precision score: {study.best_value}')
print(f'Best parameters: {study.best_params}')

# Optuna objective — CatBoost

In [38]:
def objective_catboost(trial):

    params = {
        "iterations": trial.suggest_int("iterations", 300, 800),
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 10.0),
        "loss_function": "Logloss",
        "eval_metric": "AUC",
        "random_state": random_state,
        "verbose": False
    }

    model = CatBoostClassifier(**params)

    cv_results = calculating_cross_validation(model)
    metrics_results = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]

    return metrics_results

In [ ]:
with mlflow.start_run(run_name="Catboost_hyperparameter_tuning"):
    study = optuna.create_study(direction='maximize')
    study.optimize(objective_catboost, n_trials=50)

    model = CatBoostClassifier()
    cv_results = calculating_cross_validation(model)
    metric_default_hyperparameters = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]
    catboost_best_params = study.best_params

    mlflow.log_metric('average_precision_default_params', metric_default_hyperparameters[0])
    mlflow.log_metric('best_cv_average_precision', study.best_value)
    mlflow.log_params(study.best_params)
    
print(f'Best average precision score: {study.best_params}')
print(f'Best parameters: {study.best_params}')

# Optuna objective — Extra Trees

In [20]:
def objective_extra_trees(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 800),
        "max_depth": trial.suggest_int("max_depth", 5, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "max_features": trial.suggest_float("max_features", 0.3, 1.0),
        "class_weight": "balanced",
        "random_state": config["model_training"]["random_state"],
        "n_jobs": -1
    }

    model = ExtraTreesClassifier(**params)

    cv_results = calculating_cross_validation(model)

    metrics_results = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]

    return metrics_results

In [ ]:
with mlflow.start_run(run_name="ExtraTrees_hyperparameter_tuning"):
    study = optuna.create_study(direction='maximize')
    study.optimize(objective_extra_trees, n_trials=50)

    model = ExtraTreesClassifier()
    cv_results = calculating_cross_validation(model)
    metric_default_hyperparameters = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]
    extra_trees_best_params = study.best_params
    
    mlflow.log_metric('average_precision_default_params', metric_default_hyperparameters[0])
    mlflow.log_metric('best_cv_average_precision', study.best_value)
    mlflow.log_params(study.best_params)
    
print(f'Best average precision score: {study.best_params}')
print(f'Best parameters: {study.best_params}')

# Comparison using best hyperparameters

In [49]:
catboost_best_params['random_state'] = random_state
xgb_best_params['random_state'] = random_state
extra_trees_best_params['random_state'] = random_state
xgb_best_params["scale_pos_weight"] = scale_pos_weight

In [50]:
catboost = CatBoostClassifier(**catboost_best_params)
xgboost = xgb.XGBClassifier(**xgb_best_params)
extra_tree = ExtraTreesClassifier(**extra_trees_best_params)

In [51]:
candidate_models = {
                   'CatBoost': catboost,
                   'XgBoost': xgboost,
                   'Extra Trees': extra_tree
                    }

In [52]:
#metrics that will be used for model comparison
metrics = ['Balanced Accuracy Score',
           'Precision Score',
           'Recall Score',
           'F1 Score',
           'Average Precision Score',
           'Roc AUC']

In [53]:
scoring = {
    'balanced_accuracy': 'balanced_accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'average_precision': 'average_precision',
    'roc_auc': 'roc_auc'
}

In [60]:
comparison_best_hyperparameters = pd.DataFrame(columns = metrics,
                       index= candidate_models,
                       data = 0.0)

In [61]:
comparison_best_hyperparameters

,Balanced Accuracy Score,Precision Score,Recall Score,F1 Score,Average Precision Score,Roc AUC
CatBoost,0.0,0.0,0.0,0.0,0.0,0.0
XgBoost,0.0,0.0,0.0,0.0,0.0,0.0
Extra Trees,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
with mlflow.start_run(run_name="Model_comparison_using_tuned_hyperparameters"):
    for model_name, model in candidate_models.items():
        print(f'Training model {model_name}')
    
        cv_results = cross_validate(model, 
                                    x_train, 
                                    y_train, 
                                    cv=cv, 
                                    scoring=scoring, 
                                    verbose = False)
       
        metrics_results = [cv_results[f'test_{metric}'].mean() for metric in scoring.keys()]
        print(metrics_results)
        comparison_best_hyperparameters.loc[model_name, :] = metrics_results
    comparison_best_hyperparameters.to_parquet(
        artifacts_dir / "model_selection_tuned_hyperparameters.parquet")
    mlflow.log_artifact(
        artifacts_dir / "model_selection_tuned_hyperparameters.parquet",
        artifact_path="model_selection")

Training model CatBoost
0:	learn: 0.6174762	total: 26ms	remaining: 20.5s
1:	learn: 0.5568022	total: 34.8ms	remaining: 13.7s
2:	learn: 0.4931252	total: 60.5ms	remaining: 15.9s
3:	learn: 0.4415945	total: 99.2ms	remaining: 19.5s
4:	learn: 0.3917107	total: 209ms	remaining: 32.8s
5:	learn: 0.3481057	total: 249ms	remaining: 32.5s
6:	learn: 0.3090850	total: 309ms	remaining: 34.5s
7:	learn: 0.2725843	total: 348ms	remaining: 34s
8:	learn: 0.2439648	total: 380ms	remaining: 33s
9:	learn: 0.2163485	total: 409ms	remaining: 31.9s
10:	learn: 0.1916813	total: 434ms	remaining: 30.7s
11:	learn: 0.1702970	total: 460ms	remaining: 29.8s
12:	learn: 0.1510597	total: 486ms	remaining: 29s
13:	learn: 0.1352970	total: 515ms	remaining: 28.5s
14:	learn: 0.1203625	total: 549ms	remaining: 28.3s
15:	learn: 0.1080304	total: 578ms	remaining: 27.9s
16:	learn: 0.0973937	total: 605ms	remaining: 27.5s
17:	learn: 0.0866566	total: 633ms	remaining: 27.1s
18:	learn: 0.0773792	total: 659ms	remaining: 26.7s
19:	learn: 0.0692370	total: 684ms	remaining: 26.3s
20:	learn: 0.0626589	total: 712ms	remaining: 26s
21:	learn: 0.0559815	total: 749ms	remaining: 26.1s
22:	learn: 0.0502197	total: 778ms	remaining: 25.9s
23:	learn: 0.0450445	total: 805ms	remaining: 25.6s
24:	learn: 0.0408983	total: 831ms	remaining: 25.4s
25:	learn: 0.0371132	total: 856ms	remaining: 25.1s
26:	learn: 0.0336771	total: 885ms	remaining: 25s
27:	learn: 0.0304744	total: 915ms	remaining: 24.9s
28:	learn: 0.0277880	total: 942ms	remaining: 24.7s
29:	learn: 0.0253928	total: 978ms	remaining: 24.7s
30:	learn: 0.0232617	total: 1.01s	remaining: 24.8s
31:	learn: 0.0213423	total: 1.04s	remaining: 24.6s
32:	learn: 0.0195841	total: 1.07s	remaining: 24.6s
33:	learn: 0.0180151	total: 1.11s	remaining: 24.6s
34:	learn: 0.0166083	total: 1.13s	remaining: 24.3s
35:	learn: 0.0153572	total: 1.16s	remaining: 24.2s
36:	learn: 0.0141718	total: 1.19s	remaining: 24.1s
37:	learn: 0.0131913	total: 1.22s	remaining: 24.1s
38:	learn: 0.0122530	total: 1.25s	remaining: 24s
39:	learn: 0.0114375	total: 1.27s	remaining: 23.8s
40:	learn: 0.0106993	total: 1.3s	remaining: 23.7s
41:	learn: 0.0100354	total: 1.32s	remaining: 23.5s
42:	learn: 0.0094380	total: 1.35s	remaining: 23.5s
43:	learn: 0.0088629	total: 1.38s	remaining: 23.3s
44:	learn: 0.0083604	total: 1.41s	remaining: 23.3s
45:	learn: 0.0079074	total: 1.44s	remaining: 23.2s
46:	learn: 0.0074884	total: 1.47s	remaining: 23.1s
47:	learn: 0.0070839	total: 1.49s	remaining: 23s
48:	learn: 0.0067396	total: 1.52s	remaining: 22.9s
49:	learn: 0.0064318	total: 1.54s	remaining: 22.8s
50:	learn: 0.0061330	total: 1.57s	remaining: 22.7s
51:	learn: 0.0058675	total: 1.59s	remaining: 22.6s
52:	learn: 0.0056214	total: 1.62s	remaining: 22.5s
53:	learn: 0.0053872	total: 1.65s	remaining: 22.5s
54:	learn: 0.0051790	total: 1.68s	remaining: 22.5s
55:	learn: 0.0049797	total: 1.71s	remaining: 22.4s
56:	learn: 0.0047863	total: 1.74s	remaining: 22.3s
57:	learn: 0.0046228	total: 1.77s	remaining: 22.3s
58:	learn: 0.0044560	total: 1.8s	remaining: 22.3s
59:	learn: 0.0043050	total: 1.84s	remaining: 22.3s
60:	learn: 0.0041659	total: 1.88s	remaining: 22.4s
61:	learn: 0.0040354	total: 1.92s	remaining: 22.5s
62:	learn: 0.0039154	total: 1.94s	remaining: 22.4s
63:	learn: 0.0038044	total: 1.97s	remaining: 22.3s
64:	learn: 0.0037035	total: 1.99s	remaining: 22.2s
65:	learn: 0.0036090	total: 2.02s	remaining: 22.1s
66:	learn: 0.0035173	total: 2.05s	remaining: 22.1s
67:	learn: 0.0034335	total: 2.08s	remaining: 22s
68:	learn: 0.0033546	total: 2.11s	remaining: 22s
69:	learn: 0.0032805	total: 2.13s	remaining: 21.9s
70:	learn: 0.0032049	total: 2.16s	remaining: 21.9s
71:	learn: 0.0031441	total: 2.19s	remaining: 21.8s
72:	learn: 0.0030817	total: 2.22s	remaining: 21.8s
73:	learn: 0.0030289	total: 2.25s	remaining: 21.8s
74:	learn: 0.0029714	total: 2.29s	remaining: 21.9s
75:	learn: 0.0029192	total: 2.33s	remaining: 21.9s
76:	learn: 0.0028676	total: 2.37s	remaining: 21.9s
77:	learn: 0.0028201	total: 2.4s	remaining: 21.9s
78:	learn: 0.0027804	total: 2.43s	remaining: 21.9s
79:	learn: 0.0027392	total: 2.46s	remaining: 21.8s
80:	learn: 0.0027010	total: 2.49s	remaining: 21.8s
81:	learn: 0.0026671	total: 2.52s	remaining: 21.7s
82:	learn: 0.0026316	total: 2.55s	remaining: 21.7s
83:	learn: 0.0025977	total: 2.57s	remaining: 21.6s
84:	learn: 0.0025660	total: 2.6s	remaining: 21.5s
85:	learn: 0.0025369	total: 2.62s	remaining: 21.4s
86:	learn: 0.0025094	total: 2.65s	remaining: 21.4s
87:	learn: 0.0024805	total: 2.67s	remaining: 21.3s
88:	learn: 0.0024556	total: 2.7s	remaining: 21.2s
89:	learn: 0.0024316	total: 2.73s	remaining: 21.2s
90:	learn: 0.0024078	total: 2.76s	remaining: 21.2s
91:	learn: 0.0023834	total: 2.78s	remaining: 21.1s
92:	learn: 0.0023623	total: 2.81s	remaining: 21s
93:	learn: 0.0023432	total: 2.83s	remaining: 20.9s
94:	learn: 0.0023219	total: 2.86s	remaining: 20.9s
95:	learn: 0.0023013	total: 2.88s	remaining: 20.8s
96:	learn: 0.0022844	total: 2.92s	remaining: 20.8s
97:	learn: 0.0022634	total: 2.95s	remaining: 20.8s
98:	learn: 0.0022480	total: 2.97s	remaining: 20.7s
99:	learn: 0.0022329	total: 3s	remaining: 20.7s
100:	learn: 0.0022142	total: 3.02s	remaining: 20.6s
101:	learn: 0.0022019	total: 3.05s	remaining: 20.5s
102:	learn: 0.0021853	total: 3.07s	remaining: 20.5s
103:	learn: 0.0021707	total: 3.1s	remaining: 20.4s
104:	learn: 0.0021583	total: 3.12s	remaining: 20.3s
105:	learn: 0.0021457	total: 3.15s	remaining: 20.3s
106:	learn: 0.0021328	total: 3.18s	remaining: 20.3s
107:	learn: 0.0021235	total: 3.21s	remaining: 20.2s
108:	learn: 0.0021122	total: 3.24s	remaining: 20.2s
109:	learn: 0.0021014	total: 3.26s	remaining: 20.1s
110:	learn: 0.0020905	total: 3.28s	remaining: 20.1s
111:	learn: 0.0020799	total: 3.31s	remaining: 20s
112:	learn: 0.0020689	total: 3.35s	remaining: 20.1s
113:	learn: 0.0020547	total: 3.38s	remaining: 20s
114:	learn: 0.0020455	total: 3.41s	remaining: 20s
115:	learn: 0.0020372	total: 3.44s	remaining: 20s
116:	learn: 0.0020318	total: 3.46s	remaining: 19.9s
117:	learn: 0.0020258	total: 3.49s	remaining: 19.8s
118:	learn: 0.0020187	total: 3.51s	remaining: 19.8s
119:	learn: 0.0020064	total: 3.54s	remaining: 19.7s
120:	learn: 0.0019988	total: 3.57s	remaining: 19.7s
121:	learn: 0.0019930	total: 3.6s	remaining: 19.7s
122:	learn: 0.0019854	total: 3.63s	remaining: 19.7s
123:	learn: 0.0019775	total: 3.66s	remaining: 19.6s
124:	learn: 0.0019691	total: 3.69s	remaining: 19.6s
125:	learn: 0.0019614	total: 3.71s	remaining: 19.5s
126:	learn: 0.0019562	total: 3.75s	remaining: 19.5s
127:	learn: 0.0019492	total: 3.78s	remaining: 19.5s
128:	learn: 0.0019434	total: 3.8s	remaining: 19.4s
129:	learn: 0.0019337	total: 3.83s	remaining: 19.4s
130:	learn: 0.0019204	total: 3.85s	remaining: 19.4s
131:	learn: 0.0019115	total: 3.88s	remaining: 19.3s
132:	learn: 0.0019058	total: 3.9s	remaining: 19.3s
133:	learn: 0.0019011	total: 3.93s	remaining: 19.2s
134:	learn: 0.0018950	total: 3.96s	remaining: 19.2s
135:	learn: 0.0018899	total: 3.99s	remaining: 19.1s
136:	learn: 0.0018849	total: 4.01s	remaining: 19.1s
137:	learn: 0.0018782	total: 4.04s	remaining: 19s
138:	learn: 0.0018705	total: 4.06s	remaining: 19s
139:	learn: 0.0018645	total: 4.08s	remaining: 18.9s
140:	learn: 0.0018556	total: 4.11s	remaining: 18.9s
141:	learn: 0.0018526	total: 4.14s	remaining: 18.8s
142:	learn: 0.0018462	total: 4.17s	remaining: 18.8s
143:	learn: 0.0018435	total: 4.2s	remaining: 18.8s
144:	learn: 0.0018385	total: 4.23s	remaining: 18.8s
145:	learn: 0.0018343	total: 4.25s	remaining: 18.7s
146:	learn: 0.0018289	total: 4.27s	remaining: 18.7s
147:	learn: 0.0018230	total: 4.3s	remaining: 18.6s
148:	learn: 0.0018186	total: 4.33s	remaining: 18.6s
149:	learn: 0.0018153	total: 4.36s	remaining: 18.6s
150:	learn: 0.0018123	total: 4.39s	remaining: 18.5s
151:	learn: 0.0018072	total: 4.41s	remaining: 18.5s
152:	learn: 0.0018039	total: 4.44s	remaining: 18.4s
153:	learn: 0.0017994	total: 4.46s	remaining: 18.4s
154:	learn: 0.0017947	total: 4.49s	remaining: 18.4s
155:	learn: 0.0017911	total: 4.51s	remaining: 18.3s
156:	learn: 0.0017876	total: 4.54s	remaining: 18.3s
157:	learn: 0.0017820	total: 4.56s	remaining: 18.2s
158:	learn: 0.0017769	total: 4.59s	remaining: 18.2s
159:	learn: 0.0017734	total: 4.62s	remaining: 18.2s
160:	learn: 0.0017699	total: 4.65s	remaining: 18.1s
161:	learn: 0.0017671	total: 4.67s	remaining: 18.1s
162:	learn: 0.0017607	total: 4.7s	remaining: 18.1s
163:	learn: 0.0017558	total: 4.73s	remaining: 18s
164:	learn: 0.0017503	total: 4.75s	remaining: 18s
165:	learn: 0.0017448	total: 4.79s	remaining: 18s
166:	learn: 0.0017401	total: 4.82s	remaining: 17.9s
167:	learn: 0.0017371	total: 4.85s	remaining: 17.9s
168:	learn: 0.0017348	total: 4.87s	remaining: 17.9s
169:	learn: 0.0017319	total: 4.9s	remaining: 17.8s
170:	learn: 0.0017304	total: 4.92s	remaining: 17.8s
171:	learn: 0.0017277	total: 4.95s	remaining: 17.7s
172:	learn: 0.0017243	total: 4.97s	remaining: 17.7s
173:	learn: 0.0017219	total: 5s	remaining: 17.7s
174:	learn: 0.0017191	total: 5.03s	remaining: 17.6s
175:	learn: 0.0017168	total: 5.05s	remaining: 17.6s
176:	learn: 0.0017136	total: 5.08s	remaining: 17.6s
177:	learn: 0.0017114	total: 5.11s	remaining: 17.5s
178:	learn: 0.0017086	total: 5.13s	remaining: 17.5s
179:	learn: 0.0017058	total: 5.16s	remaining: 17.4s
180:	learn: 0.0017026	total: 5.18s	remaining: 17.4s
181:	learn: 0.0016992	total: 5.21s	remaining: 17.4s
182:	learn: 0.0016927	total: 5.24s	remaining: 17.4s
183:	learn: 0.0016896	total: 5.26s	remaining: 17.3s
184:	learn: 0.0016854	total: 5.29s	remaining: 17.3s
185:	learn: 0.0016789	total: 5.33s	remaining: 17.3s
186:	learn: 0.0016743	total: 5.36s	remaining: 17.2s
187:	learn: 0.0016709	total: 5.38s	remaining: 17.2s
188:	learn: 0.0016685	total: 5.41s	remaining: 17.2s
189:	learn: 0.0016645	total: 5.43s	remaining: 17.1s
190:	learn: 0.0016620	total: 5.46s	remaining: 17.1s
191:	learn: 0.0016576	total: 5.49s	remaining: 17.1s
192:	learn: 0.0016557	total: 5.51s	remaining: 17s
193:	learn: 0.0016532	total: 5.54s	remaining: 17s
194:	learn: 0.0016511	total: 5.57s	remaining: 17s
195:	learn: 0.0016484	total: 5.6s	remaining: 16.9s
196:	learn: 0.0016453	total: 5.63s	remaining: 16.9s
197:	learn: 0.0016427	total: 5.66s	remaining: 16.9s
198:	learn: 0.0016398	total: 5.7s	remaining: 16.9s
199:	learn: 0.0016376	total: 5.72s	remaining: 16.9s
200:	learn: 0.0016358	total: 5.76s	remaining: 16.8s
201:	learn: 0.0016328	total: 5.79s	remaining: 16.8s
202:	learn: 0.0016283	total: 5.81s	remaining: 16.8s
203:	learn: 0.0016235	total: 5.83s	remaining: 16.7s
204:	learn: 0.0016212	total: 5.86s	remaining: 16.7s
205:	learn: 0.0016180	total: 5.89s	remaining: 16.7s
206:	learn: 0.0016154	total: 5.92s	remaining: 16.6s
207:	learn: 0.0016112	total: 5.94s	remaining: 16.6s
208:	learn: 0.0016088	total: 5.97s	remaining: 16.6s
209:	learn: 0.0016060	total: 5.99s	remaining: 16.5s
210:	learn: 0.0016034	total: 6.02s	remaining: 16.5s
211:	learn: 0.0016004	total: 6.04s	remaining: 16.5s
212:	learn: 0.0015976	total: 6.07s	remaining: 16.4s
213:	learn: 0.0015959	total: 6.1s	remaining: 16.4s
214:	learn: 0.0015923	total: 6.13s	remaining: 16.4s
215:	learn: 0.0015889	total: 6.15s	remaining: 16.3s
216:	learn: 0.0015867	total: 6.18s	remaining: 16.3s
217:	learn: 0.0015843	total: 6.21s	remaining: 16.3s
218:	learn: 0.0015795	total: 6.24s	remaining: 16.2s
219:	learn: 0.0015782	total: 6.26s	remaining: 16.2s
220:	learn: 0.0015753	total: 6.29s	remaining: 16.2s
221:	learn: 0.0015731	total: 6.32s	remaining: 16.1s
222:	learn: 0.0015715	total: 6.35s	remaining: 16.1s
223:	learn: 0.0015696	total: 6.37s	remaining: 16.1s
224:	learn: 0.0015633	total: 6.4s	remaining: 16s
225:	learn: 0.0015595	total: 6.42s	remaining: 16s
226:	learn: 0.0015559	total: 6.45s	remaining: 16s
227:	learn: 0.0015541	total: 6.47s	remaining: 15.9s
228:	learn: 0.0015521	total: 6.51s	remaining: 15.9s
229:	learn: 0.0015478	total: 6.54s	remaining: 15.9s
230:	learn: 0.0015447	total: 6.56s	remaining: 15.8s
231:	learn: 0.0015426	total: 6.59s	remaining: 15.8s
232:	learn: 0.0015404	total: 6.62s	remaining: 15.8s
233:	learn: 0.0015377	total: 6.65s	remaining: 15.8s
234:	learn: 0.0015355	total: 6.68s	remaining: 15.7s
235:	learn: 0.0015332	total: 6.71s	remaining: 15.7s
236:	learn: 0.0015309	total: 6.73s	remaining: 15.7s
237:	learn: 0.0015295	total: 6.76s	remaining: 15.7s
238:	learn: 0.0015253	total: 6.79s	remaining: 15.6s
239:	learn: 0.0015207	total: 6.82s	remaining: 15.6s
240:	learn: 0.0015192	total: 6.85s	remaining: 15.6s
241:	learn: 0.0015179	total: 6.88s	remaining: 15.5s
242:	learn: 0.0015165	total: 6.9s	remaining: 15.5s
243:	learn: 0.0015149	total: 6.93s	remaining: 15.5s
244:	learn: 0.0015123	total: 6.96s	remaining: 15.5s
245:	learn: 0.0015086	total: 6.99s	remaining: 15.4s
246:	learn: 0.0015070	total: 7.02s	remaining: 15.4s
247:	learn: 0.0015039	total: 7.04s	remaining: 15.4s
248:	learn: 0.0015005	total: 7.07s	remaining: 15.3s
249:	learn: 0.0014986	total: 7.09s	remaining: 15.3s
250:	learn: 0.0014961	total: 7.13s	remaining: 15.3s
251:	learn: 0.0014924	total: 7.16s	remaining: 15.3s
252:	learn: 0.0014909	total: 7.19s	remaining: 15.2s
253:	learn: 0.0014883	total: 7.22s	remaining: 15.2s
254:	learn: 0.0014859	total: 7.26s	remaining: 15.2s
255:	learn: 0.0014831	total: 7.3s	remaining: 15.2s
256:	learn: 0.0014802	total: 7.33s	remaining: 15.2s
257:	learn: 0.0014782	total: 7.38s	remaining: 15.2s
258:	learn: 0.0014762	total: 7.42s	remaining: 15.2s
259:	learn: 0.0014714	total: 7.45s	remaining: 15.2s
260:	learn: 0.0014704	total: 7.48s	remaining: 15.1s
261:	learn: 0.0014689	total: 7.5s	remaining: 15.1s
262:	learn: 0.0014665	total: 7.53s	remaining: 15.1s
263:	learn: 0.0014601	total: 7.55s	remaining: 15s
264:	learn: 0.0014592	total: 7.58s	remaining: 15s
265:	learn: 0.0014557	total: 7.61s	remaining: 15s
266:	learn: 0.0014524	total: 7.64s	remaining: 14.9s
267:	learn: 0.0014507	total: 7.69s	remaining: 14.9s
268:	learn: 0.0014467	total: 7.73s	remaining: 14.9s
269:	learn: 0.0014416	total: 7.76s	remaining: 14.9s
270:	learn: 0.0014392	total: 7.79s	remaining: 14.9s
271:	learn: 0.0014353	total: 7.82s	remaining: 14.9s
272:	learn: 0.0014327	total: 7.84s	remaining: 14.8s
273:	learn: 0.0014309	total: 7.88s	remaining: 14.8s
274:	learn: 0.0014268	total: 7.91s	remaining: 14.8s
275:	learn: 0.0014245	total: 7.93s	remaining: 14.7s
276:	learn: 0.0014229	total: 7.96s	remaining: 14.7s
277:	learn: 0.0014210	total: 7.99s	remaining: 14.7s
278:	learn: 0.0014192	total: 8.02s	remaining: 14.7s
279:	learn: 0.0014173	total: 8.05s	remaining: 14.6s
280:	learn: 0.0014150	total: 8.09s	remaining: 14.6s
281:	learn: 0.0014130	total: 8.12s	remaining: 14.6s
282:	learn: 0.0014110	total: 8.16s	remaining: 14.6s
283:	learn: 0.0014089	total: 8.2s	remaining: 14.6s
284:	learn: 0.0014058	total: 8.23s	remaining: 14.6s
285:	learn: 0.0014027	total: 8.27s	remaining: 14.5s
286:	learn: 0.0013984	total: 8.31s	remaining: 14.5s
287:	learn: 0.0013970	total: 8.35s	remaining: 14.5s
288:	learn: 0.0013944	total: 8.37s	remaining: 14.5s
289:	learn: 0.0013921	total: 8.39s	remaining: 14.4s
290:	learn: 0.0013899	total: 8.42s	remaining: 14.4s
291:	learn: 0.0013887	total: 8.44s	remaining: 14.4s
292:	learn: 0.0013858	total: 8.47s	remaining: 14.3s
293:	learn: 0.0013843	total: 8.49s	remaining: 14.3s
294:	learn: 0.0013805	total: 8.52s	remaining: 14.3s
295:	learn: 0.0013779	total: 8.54s	remaining: 14.2s
296:	learn: 0.0013759	total: 8.57s	remaining: 14.2s
297:	learn: 0.0013750	total: 8.6s	remaining: 14.2s
298:	learn: 0.0013728	total: 8.62s	remaining: 14.1s
299:	learn: 0.0013705	total: 8.65s	remaining: 14.1s
300:	learn: 0.0013691	total: 8.67s	remaining: 14.1s
301:	learn: 0.0013658	total: 8.69s	remaining: 14s
302:	learn: 0.0013640	total: 8.72s	remaining: 14s
303:	learn: 0.0013629	total: 8.74s	remaining: 14s
304:	learn: 0.0013599	total: 8.78s	remaining: 13.9s
305:	learn: 0.0013577	total: 8.81s	remaining: 13.9s
306:	learn: 0.0013555	total: 8.85s	remaining: 13.9s
307:	learn: 0.0013517	total: 8.88s	remaining: 13.9s
308:	learn: 0.0013507	total: 8.91s	remaining: 13.8s
309:	learn: 0.0013483	total: 8.97s	remaining: 13.9s
310:	learn: 0.0013430	total: 9.01s	remaining: 13.8s
311:	learn: 0.0013406	total: 9.04s	remaining: 13.8s
312:	learn: 0.0013386	total: 9.07s	remaining: 13.8s
313:	learn: 0.0013358	total: 9.11s	remaining: 13.8s
314:	learn: 0.0013335	total: 9.14s	remaining: 13.8s
315:	learn: 0.0013274	total: 9.19s	remaining: 13.8s
316:	learn: 0.0013250	total: 9.22s	remaining: 13.7s
317:	learn: 0.0013223	total: 9.25s	remaining: 13.7s
318:	learn: 0.0013176	total: 9.29s	remaining: 13.7s
319:	learn: 0.0013146	total: 9.32s	remaining: 13.7s
320:	learn: 0.0013104	total: 9.34s	remaining: 13.6s
321:	learn: 0.0013059	total: 9.37s	remaining: 13.6s
322:	learn: 0.0013031	total: 9.4s	remaining: 13.6s
323:	learn: 0.0013000	total: 9.42s	remaining: 13.5s
324:	learn: 0.0012987	total: 9.45s	remaining: 13.5s
325:	learn: 0.0012970	total: 9.47s	remaining: 13.5s
326:	learn: 0.0012939	total: 9.5s	remaining: 13.4s
327:	learn: 0.0012914	total: 9.52s	remaining: 13.4s
328:	learn: 0.0012891	total: 9.55s	remaining: 13.4s
329:	learn: 0.0012860	total: 9.58s	remaining: 13.3s
330:	learn: 0.0012825	total: 9.61s	remaining: 13.3s
331:	learn: 0.0012781	total: 9.64s	remaining: 13.3s
332:	learn: 0.0012750	total: 9.67s	remaining: 13.2s
333:	learn: 0.0012727	total: 9.7s	remaining: 13.2s
334:	learn: 0.0012706	total: 9.72s	remaining: 13.2s
335:	learn: 0.0012673	total: 9.75s	remaining: 13.1s
336:	learn: 0.0012647	total: 9.77s	remaining: 13.1s
337:	learn: 0.0012636	total: 9.8s	remaining: 13.1s
338:	learn: 0.0012625	total: 9.83s	remaining: 13s
339:	learn: 0.0012612	total: 9.86s	remaining: 13s
340:	learn: 0.0012562	total: 9.89s	remaining: 13s
341:	learn: 0.0012535	total: 9.92s	remaining: 13s
342:	learn: 0.0012527	total: 9.95s	remaining: 12.9s
343:	learn: 0.0012502	total: 9.99s	remaining: 12.9s
344:	learn: 0.0012486	total: 10s	remaining: 12.9s
345:	learn: 0.0012472	total: 10.1s	remaining: 12.9s
346:	learn: 0.0012446	total: 10.1s	remaining: 12.9s
347:	learn: 0.0012428	total: 10.1s	remaining: 12.8s
348:	learn: 0.0012417	total: 10.2s	remaining: 12.8s
349:	learn: 0.0012392	total: 10.2s	remaining: 12.8s
350:	learn: 0.0012379	total: 10.2s	remaining: 12.8s
351:	learn: 0.0012368	total: 10.3s	remaining: 12.8s
352:	learn: 0.0012350	total: 10.3s	remaining: 12.8s
353:	learn: 0.0012341	total: 10.4s	remaining: 12.8s
354:	learn: 0.0012314	total: 10.4s	remaining: 12.7s
355:	learn: 0.0012300	total: 10.5s	remaining: 12.7s
356:	learn: 0.0012289	total: 10.5s	remaining: 12.7s
357:	learn: 0.0012272	total: 10.5s	remaining: 12.7s
358:	learn: 0.0012258	total: 10.6s	remaining: 12.7s
359:	learn: 0.0012237	total: 10.6s	remaining: 12.6s
360:	learn: 0.0012215	total: 10.6s	remaining: 12.6s
361:	learn: 0.0012176	total: 10.7s	remaining: 12.6s
362:	learn: 0.0012156	total: 10.7s	remaining: 12.6s
363:	learn: 0.0012118	total: 10.7s	remaining: 12.5s
364:	learn: 0.0012100	total: 10.8s	remaining: 12.5s
365:	learn: 0.0012081	total: 10.8s	remaining: 12.5s
366:	learn: 0.0012047	total: 10.8s	remaining: 12.5s
367:	learn: 0.0012008	total: 10.9s	remaining: 12.4s
368:	learn: 0.0011992	total: 10.9s	remaining: 12.4s
369:	learn: 0.0011948	total: 10.9s	remaining: 12.4s
370:	learn: 0.0011920	total: 10.9s	remaining: 12.3s
371:	learn: 0.0011881	total: 11s	remaining: 12.3s
372:	learn: 0.0011850	total: 11s	remaining: 12.3s
373:	learn: 0.0011833	total: 11s	remaining: 12.2s
374:	learn: 0.0011812	total: 11.1s	remaining: 12.2s
375:	learn: 0.0011803	total: 11.1s	remaining: 12.2s
376:	learn: 0.0011776	total: 11.1s	remaining: 12.2s
377:	learn: 0.0011758	total: 11.2s	remaining: 12.2s
378:	learn: 0.0011747	total: 11.3s	remaining: 12.2s
379:	learn: 0.0011727	total: 11.3s	remaining: 12.2s
380:	learn: 0.0011676	total: 11.4s	remaining: 12.2s
381:	learn: 0.0011661	total: 11.4s	remaining: 12.2s
382:	learn: 0.0011643	total: 11.4s	remaining: 12.1s
383:	learn: 0.0011619	total: 11.5s	remaining: 12.1s
384:	learn: 0.0011590	total: 11.5s	remaining: 12.1s
385:	learn: 0.0011574	total: 11.6s	remaining: 12.1s
386:	learn: 0.0011542	total: 11.6s	remaining: 12s
387:	learn: 0.0011513	total: 11.6s	remaining: 12s

In [68]:
comparison_best_hyperparameters

,Balanced Accuracy Score,Precision Score,Recall Score,F1 Score,Average Precision Score,Roc AUC
CatBoost,0.895811,0.960413,0.791678,0.867607,0.860184,0.984145
XgBoost,0.918403,0.906378,0.836952,0.869870,0.867680,0.978355
Extra Trees,0.891253,0.942505,0.782587,0.854783,0.857175,0.985061